<a href="https://colab.research.google.com/github/hafsaaaaaaaa/MLPROJECT_/blob/main/titanic_NAIVE_BAYES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df = pd.read_csv("/content/archive (3).zip")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [6]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

input sex= input sex.map{male:1,female:2}

In [7]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       0     1

In [8]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age    Fare  female  male
0       3    male  34.5  7.8292       0     1
1       3  female  47.0  7.0000       1     0
2       2    male  62.0  9.6875       0     1

I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [9]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age    Fare  female
0       3  34.5  7.8292       0
1       3  47.0  7.0000       1
2       2  62.0  9.6875       0

In [10]:
inputs.columns[inputs.isna().any()]

Index(['Age', 'Fare'], dtype='object')

In [11]:
inputs.Age[:10]

0    34.5
1    47.0
2    62.0
3    27.0
4    22.0
5    14.0
6    30.0
7    26.0
8    18.0
9    21.0
Name: Age, dtype: float64

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass   Age     Fare  female
0       3  34.5   7.8292       0
1       3  47.0   7.0000       1
2       2  62.0   9.6875       0
3       3  27.0   8.6625       0
4       3  22.0  12.2875       1
5       3  14.0   9.2250       0

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [34]:
len(X_train)

334

In [35]:
len(X_test)

84

In [36]:
len(inputs)

418

In [37]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [38]:
model.fit(X_train, y_train)

GaussianNB()

In [43]:
accuracy = model.score(X_test, y_test)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [44]:
X_test[0:10]

     Pclass       Age      Fare  female
264       2  30.00000   12.7375       0
309       3  45.00000   14.1083       1
399       3  31.00000    7.7333       0
331       1  39.00000   29.7000       0
24        1  48.00000  262.3750       1
201       3   0.33000   14.4000       0
85        3  30.27259   14.4542       0
170       3  30.27259    7.5500       0
176       2  20.00000   36.7500       1
311       3  22.00000    7.2250       0

In [45]:
y_test[0:10]

264    0
309    1
399    0
331    0
24     1
201    0
85     0
170    0
176    1
311    0
Name: Survived, dtype: int64

In [46]:
model.predict(X_test[0:10])

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0])

In [47]:
model.predict_proba(X_test[:10])

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

here we have 2 samples first one mean that there is 1 percent of change that he will not survivied and 0 percent for survived so in first case our model predict that the passasnger is died because he have 0 percent chance